{% set name = "attr" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://download.savannah.gnu.org/releases/attr/attr-{{ version }}.tar.gz
  sha256: bae1c6949b258a0d68001367ce0c741cebdacdd3b62965d17e5eb23cd78adaf8

build:
  number: 1
  skip: true  # [not linux]
  run_exports:
    - {{ pin_subpackage('attr', max_pin='x.x') }}

requirements:
  build:
    - gnuconfig  # [unix]
    - {{ compiler('c') }}
    - make

test:
  commands:
    - attr -l "${PREFIX}/bin/attr"

about:
  home: http://savannah.nongnu.org/projects/attr
  license: GPL-2.0-or-later
  license_family: GPL
  license_file:
    - doc/COPYING
    - doc/COPYING.LGPL
  summary: Commands for Manipulating Filesystem Extended Attributes

extra:
  recipe-maintainers:
    - scopatz
    - saraedum
