{% set name = "attr" %}
{% set version = "2.4.48" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: http://download.savannah.gnu.org/releases/attr/attr-{{ version }}.tar.gz
  sha256: 5ead72b358ec709ed00bbf7a9eaef1654baad937c001c044fe8b74c57f5324e7

build:
  number: 0
  skip: true  # [win]
  run_exports:
    - {{ pin_subpackage('attr', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('c') }}
    - make

test:
  commands:
    - attr -l "${PREFIX}/bin/attr"

about:
  home: http://savannah.nongnu.org/projects/attr
  license: GPL-2.0-or-later
  license_family: GPL
  license_file:
    - doc/COPYING
    - doc/COPYING.LGPL
  summary: 'Commands for Manipulating Filesystem Extended Attributes'

extra:
  recipe-maintainers:
    - scopatz
    - saraedum
