travis:
  secure:
    BINSTAR_TOKEN: U+XNPpfIuQ/5kKnKnJi6kmmKe/U42yQaYz71lKQVehGe/wGd8Fht/3f4QJdSgrIgU4X+lDJFYxSeoFdX6mSbFSqmBRd1RDfy6kjKW20QKsnNx/z/PNSVkx7udabAQuLWYjYvLoiVkC+fG8XFQ/bi/b+67bf+AN0LLz20tmlUIku+9fDl5jX3UPPgYCljVFkiEmSHbrqm8hOLlU6YEVX3dUkwPEnO341hYXiSRAlVox3wT1cjXBKFOpAC04h1tg8rrhS2E0ybAOe21vYfr3BiSbs0/z5ULz93J70ygxaAGZ/wX2L+/1mIlMvjK3/NHPbJSF9PZiYnig3HFu8p8GaWVofUKEAin7Ai0M0qa4TkbKnA9RwN1ZnhirEM+bE0A6DdF/mHILwkou+QiOES0B3/gU238eGQ7fvbGDEkq1/cGOoSa9CtPi/xqhij6wTQVYwhppU+HzC8rOmIlWoa31QvAxUqi0EqtvS6eqBGfU4kDzOU5vr6otO5ED/VwKyQTZw7IwzP2ybYcmET9pOwcc71zRVFbjMKFxlRXYtCbk1W4BNlWvWTYBA8rv9VUBWUE1vM6AGQkds+cNEv9Em4Bd5hXso8Rv+IlKs5fQQbQXvGmXZnrA6A4Bnpo9WqqMGpAAE9ynGzljEmfl1iS/NZSGXEqJ5XwtU3Vd1W1OLGaN5rbn4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  linux_aarch64: default
